//
// Created by dlwog on 25. 11. 20..
//

#ifndef MYPROJECT_MML_OP_HPP
#define MYPROJECT_MML_OP_HPP

enum v_operation
{
  v_OP_NONE = 0,

  v_OP_DUP,
  v_OP_ADD,
  v_OP_ADD_ID,
  v_OP_ADD1,
  v_OP_ACC,
  v_OP_SUB,
  v_OP_MUL,
  v_OP_DIV,
  v_OP_SQR,
  v_OP_SQRT,
  v_OP_LOG,
  v_OP_SIN,
  v_OP_COS,
  v_OP_SUM,
  v_OP_SUM_ROWS,
  V_OP_MEAN,
  V_OP_ARGMAX,
  v_OP_COUNT_EQUAL,
  v_OP_REPEAT,
  v_OP_REPEAT_BACK,
  v_OP_CONCAT,
  v_OP_SILU_BACK,
  v_OP_NORM, // normalize
  v_OP_RMS_NORM,
  v_OP_RMS_NORM_BACK,
  v_OP_GROUP_NORM,
  v_OP_L2_NORM,

  v_OP_MUL_MAT,
  v_OP_MUL_MAT_ID,
  V_OP_OUT_PROD,

  V_OP_SCALE,
  v_OP_SET,
  v_OP_CPY,
  v_OP_CONT,
  v_OP_RESHAPE,
  V_OP_VIEW,
  V_OP_PERMUTE,
  v_OP_TRANSPOSE,
  v_OP_GET_ROWS,
  V_OP_GET_ROWS_BACK,
  v_OP_SET_ROWS,
  V_OP_DIAG,
  V_OP_DIAG_MASK_INF,
  V_OP_DIAG_MASK_ZERO,
  V_OP_SOFT_MAX,
  v_OP_SOFT_MAX_BACK,
  V_OP_ROPE,
  v_OP_ROPE_BACK,
  v_OP_CLAMP,
  v_OP_CONV_TRANSPOSE_1D,
  V_OP_IM2COL,
  v_OP_IM2COL_BACK,
  v_OP_IM2COL_3D,
  v_OP_CONV_2D,
  v_OP_CONV_3D,
  v_OP_CONV_2D_DW,
  v_OP_CONV_TRANSPOSE_2D,
  v_OP_POOL_1D,
  V_OP_POOL_2D,
  V_OP_POOL_2D_BACK,
  v_OP_UPSCALE,
  v_OP_PAD,
  v_OP_PAD_REFLECT_1D,
  v_OP_ROLL,
  v_OP_ARANGE,
  v_OP_TIMESTEP_EMBEDDING,
  v_OP_ARGSORT,
  v_OP_LEAKY_RELU,

  v_OP_FLASH_ATTN_EXT,
  v_OP_FLASH_ATTN_BACK,
  v_OP_SSM_CONV,
  v_OP_SSM_SCAN,
  v_OP_WIN_PART,
  v_OP_WIN_UNPART,
  v_OP_GET_REL_POS,
  v_OP_ADD_REL_POS,
  v_OP_RWKV_WKV6,
  v_OP_GATED_LINEAR_ATTN,
  v_OP_RWKV_WKV7,

  v_OP_UNARY,

  v_OP_MAP_CUSTOM1,
  v_OP_MAP_CUSTOM2,
  v_OP_MAP_CUSTOM3,

  v_OP_CUSTOM,

  v_OP_CROSS_ENTROPY_LOSS,
  v_OP_CROSS_ENTROPY_LOSS_BACK,
  v_OP_OPT_STEP_ADAMW,
  v_OP_OPT_STEP_SGD,

  v_OP_GLU,

  v_OP_COUNT,
};

enum v_unary_op
{
  v_UNARY_OP_ABS,
  v_UNARY_OP_SGN,
  v_UNARY_OP_NEG,
  v_UNARY_OP_STEP,
  v_UNARY_OP_TANH,
  v_UNARY_OP_ELU,
  v_UNARY_OP_RELU,
  v_UNARY_OP_SIGMOID,
  v_UNARY_OP_GELU,
  v_UNARY_OP_GELU_QUICK,
  v_UNARY_OP_SILU,
  v_UNARY_OP_HARDSWISH,
  v_UNARY_OP_HARDSIGMOID,
  v_UNARY_OP_EXP,
  v_UNARY_OP_GELU_ERF,
  v_UNARY_OP_XIELU,
  v_UNARY_OP_FLOOR,
  v_UNARY_OP_CEIL,
  v_UNARY_OP_ROUND,

  v_UNARY_OP_TRUNC,
  v_UNARY_OP_LOG,
  v_UNARY_OP_COUNT,
  v_UNARY_OP_RAND_GEN,
};

enum v_glu_op
{
  v_GLU_OP_REGLU,
  v_GLU_OP_GEGLU,
  v_GLU_OP_SWIGLU,
  v_GLU_OP_SWIGLU_OAI,
  v_GLU_OP_GEGLU_ERF,
  v_GLU_OP_GEGLU_QUICK,
  v_GLU_OP_COUNT,
};

#endif //MYPROJECT_MML_OP_HPP